version: "3.9"

services:
  next-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
